# docker-compose.yaml
version: '3.8'

services:
  nginx:
    image: ghcr.io/${GITHUB_USERNAME}/nginx-test-pull-image-app:sha-6770072
    container_name: nginx-test
    ports:
      - "8080:80"
    environment:
      - DOCKER_REGISTRY=ghcr.io
      - DOCKER_USERNAME=${GITHUB_USERNAME}
      - DOCKER_PASSWORD=${GHCR_PULL_IMAGE_TOKEN}
    restart: unless-stopped